config/routes.rb
Rails.application.routes.draw do
  resources :cats
  root to: 'cats#index'

  resources :cat_versions, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  before_save { self.email = email.downcase }
  after_commit :send_changes_to_version_history, on: :update, if: :persisted?

  has_one_attached :avatar, dependent: :destroy
  has_many :cat_versions, dependent: :destroy

  enum status: [:single, :open_relationship, :just_friendship]

  validates :name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  private

  def send_changes_to_version_history
    new_version = Hash.new

    self.previous_changes.each do |key, changes|
      next if key == ("updated_at" || "created_at" || "id")
      new_version[key] = changes.last
    end

    self.cat_versions.create!(new_version)
  end
end

app/models/cat_version.rb
class CatVersion < ApplicationRecord
  belongs_to :cat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_versions_controller.rb
class CatVersionsController < ApplicationController
  def show
    @versions = CatVersion.where(cat_id: params[:id])

    if @versions.blank?
      return render json: { message: "Cat not found" }, status: :not_found
    end
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :require_cat, only: [:show, :destroy, :update, :edit]

  def index
    @cats = Cat.all
  end

  def show
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = Cat.new(cats_params)
    @cat.save

    redirect_to cats_path
  end

  def edit
  end

  def update
    @cat.update(cats_params)
    redirect_to cat_path(@cat.id)
  end

  def destroy
    @cat.destroy

    redirect_to cats_path
  end

  private

  def cats_params
    params.require(:cat).permit(
      :id,
      :name,
      :last_name,
      :email,
      :phone,
      :status,
      :avatar
    )
  end

  def current_cat
    @cat = Cat.find_by(id: params[:id])
  end

  def require_cat
    if current_cat.blank?
      return render json: { message: "Cat not found" }, status: :not_found
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_versions/show.html.erb
<div class="flex flex-col w-full mt-12">
  <%= link_to '<- More Cats', cats_path, class: "text-violet-700 focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="border-b">
          <tr>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
              Name
            </th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
              Phone
            </th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
              Email
            </th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
              Status
            </th>
            <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
              Change made at
            </th>
          </tr>
          </thead>
          <tbody>
          <% @versions.each do |version| %>
            <tr class="bg-white border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                <%= version.name %>  <%= version.last_name %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= version.phone %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= version.email %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= version.status %>
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                <%= version.created_at %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/cats/_form.html.erb
<%= form_with model: @cat, local: true do |form| %>
  <div class="shadow sm:overflow-hidden sm:rounded-md">
    <div class="space-y-6 bg-white px-4 py-5 sm:p-6">
      <div class="grid md:grid-cols-2 gap-6">
        <div class="md:col-span-1">
          <%= form.label :name, "First name:", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_field :name, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
        </div>
        <div>
          <%= form.label :last_name, "Last name:", class: "block text-sm font-medium text-gray-700" %>
          <%= form.text_field :last_name, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
        </div>
      </div>
      <div class="w-full">
        <%= form.label :email, "Email address:", class: "block text-sm font-medium text-gray-700" %>
        <%= form.email_field :email, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", autocomplete: "email" %>
      </div>
      <div class="w-full">
        <%= form.label :phone, "Phone:", class: "block text-sm font-medium text-gray-700" %>
        <%= form.telephone_field :phone, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm", autocomplete: "695272918" %>
      </div>
      <fieldset>
        <legend class="text-sm font-medium text-gray-700">
          Sentimental status
        </legend>
        <p class="text-sm text-gray-500 mt-2">
          What are you currently looking for?
        </p>
        <div class="mt-4 space-y-4">
          <%= form.select :status, options_for_select(Cat.statuses.keys.map{ |key| [key.humanize, key] }, selected: 'single'), {}, { :class => 'rounded-md border-gray-300 text-indigo-600 focus:ring-indigo-500' } %>
        </div>
      </fieldset>
      <div>
        <label class="block text-sm font-medium text-gray-700">Cover photo</label>
        <div class="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
          <div class="space-y-1 text-center">
            <svg class="mx-auto h-12 w-12 text-gray-400" stroke="currentColor" fill="none" viewBox="0 0 48 48" aria-hidden="true">
              <path d="M28 8H12a4 4 0 00-4 4v20m32-12v8m0 0v8a4 4 0 01-4 4H12a4 4 0 01-4-4v-4m32-4l-3.172-3.172a4 4 0 00-5.656 0L28 28M8 32l9.172-9.172a4 4 0 015.656 0L28 28m0 0l4 4m4-24h8m-4-4v8m-12 4h.02" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
            <div class="flex text-sm text-gray-600">
              <label for="avatar" class="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500">
                <span>Upload a file</span>
                <%= form.file_field :avatar %>
              </label>
            </div>
            <p class="text-xs text-gray-500">PNG, JPG, GIF up to 10MB</p>
          </div>
        </div>
      </div>
    </div>
    <div class="bg-gray-50 px-4 py-3 text-right sm:px-6">
      <%= form.submit "Save", class: "inline-flex justify-center rounded-md border border-transparent bg-violet-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
  </div>
<% end %>

app/views/cats/edit.html.erb
<div class="container mx-auto max-w-screen-lg max-h-screen my-8">
  <%= link_to '<- More Cats', cats_path, class: "text-violet-700 focus:outline-none text-sm py-2 cursor-pointer" %>
  <div class="md:grid md:grid-cols-3 md:gap-6 mt-16">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900">
          Profile
        </h3>
        <p class="mt-1 text-sm text-gray-600">
          Edit your profile
        </p>
      </div>
    </div>
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/cats/index.html.erb
<div class="container mx-auto my-8">
  <div class="flex justify-between items-center w-full">
    <h1 class="text-violet-800 font-medium text-4xl">
      Tinder for kittens
    </h1>
    <%= link_to '+ New Cat', new_cat_path, class: "rounded-full bg-violet-300 text-violet-700 focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
  </div>
  <div class="grid grid-cols-1 md:grid-cols-3 md:gap-x-4 gap-y-4 mt-12">
    <% @cats.each do |cat| %>
      <div class="rounded-lg border border-gray-300 w-full h-full">
        <div class="md:col-span-3 aspect-w-3 aspect-h-2 overflow-hidden rounded-lg">
          <% if cat.avatar.attached? %>
            <img src="<%= url_for(cat.avatar) %>" alt="Cat avatar" class="h-full w-full object-cover object-center">
          <% end %>
        </div>
        <div class="md:col-span-2 bg-white mx-5 flex flex-col items-center justify-center py-5">
          <p class="text-violet-800 text-lg">
            <%= cat.name %> <%= cat.last_name %>
          </p>
          <% if cat.status.present? %>
            <p class="text-gray-700 mt-2 text-sm">
              <%= cat.status.humanize %>
            </p>
          <% end %>
          <div class="flex justify-between items-center mt-4 w-1/2 mx-auto">
            <%= link_to 'Like', cat_path(cat), class: "rounded-full bg-violet-300 text-violet-700 focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
            <%= button_to 'Dislike', cat_path(cat), method: :delete, data: { confirm: 'Are you sure?' }, class: "rounded-full bg-orange-200 text-orange-600 text-white focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cats/new.html.erb
<div class="container mx-auto max-w-screen-lg max-h-screen my-8">
  <%= link_to '<- More Cats', cats_path, class: "text-violet-700 focus:outline-none text-sm py-2 cursor-pointer" %>
  <div class="md:grid md:grid-cols-3 md:gap-6 mt-16">
    <div class="md:col-span-1">
      <div class="px-4 sm:px-0">
        <h3 class="text-lg font-medium leading-6 text-gray-900">
          Profile
        </h3>
        <p class="mt-1 text-sm text-gray-600">
          tell us a bit about yourself and your interests.
        </p>
      </div>
    </div>
    <div class="mt-5 md:col-span-2 md:mt-0">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/cats/show.html.erb
<div class="container mx-auto max-h-screen my-8">
  <%= link_to '<- More Cats', cats_path, class: "text-violet-700 focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
  <div class="grid grid-cols-1 md:grid-cols-5 rounded-lg border border-gray-300 w-full h-full mt-12">
    <div class="md:col-span-3 aspect-w-3 aspect-h-2 overflow-hidden rounded-lg">
      <img src="<%= url_for(@cat.avatar) %>" alt="Cat avatar" class="h-full w-full object-cover object-center">
    </div>
    <div class="md:col-span-2 bg-white px-5 flex flex-col items-center justify-center w-full h-full bg-violet-100">
      <h2 class="text-violet-800 text-4xl">
        <%= @cat.name %> <%= @cat.last_name %>
      </h2>
      <% if @cat.status.present? %>
        <p class="text-gray-700 mt-2 text-sm">
          <%= @cat.status.humanize %>
        </p>
      <% end %>
      <p class="text-gray-700 mt-2 text-sm">
        <%= @cat.email %>
      </p>
      <p class="text-gray-700 mt-2 text-sm">
        <%= @cat.phone %>
      </p>
      <div class="flex justify-between items-center mt-4 w-1/2 mx-auto">
        <%= link_to 'Edit', edit_cat_path(@cat), class: "rounded-full bg-violet-300 text-violet-700 focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
        <%= link_to 'See history', cat_version_path(@cat), class: "rounded-full bg-orange-200 text-orange-600 text-white focus:outline-none text-sm px-4 py-2 cursor-pointer" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinderForCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <main class="container mx-auto px-5 text-2xl">
      <%= yield %>
    </main>
  </body>
</html>